# String Lookups expected in the Dataframes containing Consumption data
INCLINE = "incline"
T_AMB = "t_amb"
LEVEL_OF_LOADING = "level_of_loading"
SPEED = "mean_speed_kmh"
CONSUMPTION = "consumption_kwh_per_km"
VEHICLE_TYPE = "vehicle_type"
TEMPERATURE = "temperature"
LONGITUDE = "lng"
LATITUDE = "lat"
ELEVATION = "elevation"
